mysql:
  addr: 159.27.184.52
  port: 6033
  username: root
  password: Zhangzhengxu123.
  database: ByteQingXun

redis:
  addr: 159.27.184.52
  port: 9763
  password: Zhangzhengxu123.

rabbitmq:
  addr: 159.27.184.52:5672
  username: guest
  password: Zhangzhengxu123.

etcd:
  address: 159.27.184.52:2379

server:
  addr: 127.0.0.1:8086
  domain: rpcInteractionService